Proposal to show tx on success plus --json option
0chain/zwalletcli pull request #129
Opened 2022-05-16 20:01 UTC by sculptex

Combined request to solve https://github.com/0chain/zwalletcli/issues/51 and add --json option @stewartie4 

Invalid json response will indicate error unless we format all responses as json when requested

A brief description of the changes in this PR:

Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/zwalletcli/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- 0chain:
- Other: ...

2022-05-23 07:13 UTC, cnlangzi requested changes

2022-05-23 07:13 UTC, cnlangzi commented on cmd/send.go
> +				fmt.Println("Send tokens success:", txn.Hash())
revert it to fix system_test.
```suggestion
fmt.Println("Send tokens success:")
```

2022-05-23 07:16 UTC, cnlangzi requested changes

2022-05-23 07:16 UTC, cnlangzi commented on cmd/send.go
> +fmt.Println("Send tokens success:")
```suggestion
				fmt.Println("Send tokens success")
```

2022-05-23 07:29 UTC, cnlangzi approved these changes
LGTM

2022-05-23 08:53 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/print_hash_on_send  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | sculptex-sendtxjson  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-05-23 09:44 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/print_hash_on_send  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | sculptex-sendtxjson  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-05-25 06:27 UTC, Kishan-Dhakan approved these changes
LGTM

2022-05-25 09:10 UTC, merged