Mn pool info related doc update
0chain/zwalletcli pull request #160
Opened 2022-07-24 20:52 UTC by iamrz1

2022-08-27 19:38 UTC, dabasov approved these changes
lgtm

2022-11-01 04:19 UTC, peterlimg approved these changes
lgtm

2022-11-01 04:33 UTC, peterlimg requested changes

2022-11-01 04:33 UTC, peterlimg commented on README.md
> +| `--pool_id` | No       | Pool ID of a stake (get at `mn-info` or `mn-user-info`)      |         |              |
Seems this command does not have `pool_id` option anymore.

2023-03-03 00:48 UTC, peterlimg approved these changes
LGTM

2023-05-21 00:37 UTC, merged