add fees support for mainnet transaction
0chain/zwalletcli pull request #184
Opened 2022-10-06 08:13 UTC by bisakhmondal

A brief description of the changes in this PR:

closes: #85 

Incorporate
- `withFee` flag
- singleton `transactionFee` get method
- (TODO): in absence of withFee fallback to min_fee captured from blockchain

Tasks to complete before merging PR:
- [x]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/zwalletcli/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- 0chain:
- Other: ...

2022-10-09 09:46 UTC, dabasov requested changes

2022-10-09 09:46 UTC, dabasov commented on cmd/root.go
> +var MinTxFee float64
we should use int64 in SAS

2022-10-09 09:46 UTC, dabasov commented on cmd/root.go
> +var txFee float64
the same int64 in SAS

2022-10-25 17:57 UTC, dabasov approved these changes
lgtm

2022-10-25 18:00 UTC, dabasov approved these changes
lgtm

2022-10-25 18:00 UTC, dabasov commented
please fix tests @bisakhmondal

2022-10-26 21:41 UTC, bisakhmondal commented
> please fix tests @bisakhmondal

On it.

2022-10-27 20:26 UTC, bisakhmondal commented
> please fix tests @bisakhmondal

Hey @dabasov, I think we have to deploy the 0chain core to devnet for the estimate_tx_cost API
![image](https://user-images.githubusercontent.com/41498427/198390898-bd133ac5-bd9f-4ff2-98ab-cbcdcc2c5776.png)

Any heads up on how to do that?

2022-11-01 16:10 UTC, dabasov approved these changes
lgtm

2022-11-09 05:22 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | chain-fee-integration  |
| gosdk  | chain-fee  |
| zboxcli  | chain-fee  |
| zwalletcli  | feat/chain-fee  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-12-06 06:26 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | chain-fee  |
| zwalletcli  | feat/chain-fee  |
| 0chain  | chain-fee  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-12-07 06:25 UTC, service-0chain commented
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | chain-fee  |
| zwalletcli  | feat/chain-fee  |
| 0chain  | chain-fee  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-01-27 09:53 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | chain-fee  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | chain-fee  |
| zwalletcli  | feat/chain-fee  |
| 0chain  | chain-fee  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-02-16 00:05 UTC, service-0chain commented
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | chain-fee  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | chain-fee  |
| zwalletcli  | feat/chain-fee  |
| 0chain  | chain-fee  |
| blobber  | chain-fee  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-02-16 23:34 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | chain-fee  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | chain-fee  |
| zwalletcli  | feat/chain-fee  |
| 0chain  | chain-fee  |
| blobber  | chain-fee  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-02-17 09:33 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | chain-fee  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | chain-fee  |
| zwalletcli  | feat/chain-fee  |
| 0chain  | chain-fee  |
| blobber  | chain-fee  |
| authorizer  | chain-fee  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-02-18 06:44 UTC, service-0chain commented
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | chain-fee  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | chain-fee  |
| zwalletcli  | feat/chain-fee  |
| 0chain  | chain-fee  |
| blobber  | chain-fee  |
| authorizer  | chain-fee  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-02-26 21:24 UTC, boddumanohar commented
@dabasov are these changes good to merge?

2023-02-27 19:47 UTC, service-0chain commented
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | chain-fee  |
| gosdk  | chain-fee  |
| zboxcli  | chain-fee  |
| zwalletcli  | feat/chain-fee  |
| 0chain  | chain-fee  |
| blobber  | chain-fee  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-02-27 19:59 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | chain-fee  |
| gosdk  | chain-fee  |
| zboxcli  | chain-fee  |
| zwalletcli  | feat/chain-fee  |
| 0chain  | chain-fee  |
| blobber  | chain-fee  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-03-01 18:41 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | chain-fee  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | chain-fee  |
| zwalletcli  | feat/chain-fee  |
| 0chain  | chain-fee  |
| blobber  | chain-fee  |
| authorizer  | chain-fee  |
| 0box  | chain-fee  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-03-04 07:45 UTC, service-0chain commented
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | chain-fee  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | chain-fee  |
| zwalletcli  | feat/chain-fee  |
| 0chain  | chain-fee  |
| blobber  | chain-fee  |
| authorizer  | chain-fee  |
| 0box  | chain-fee  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-03-13 19:59 UTC, service-0chain commented
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | ABILITY TO SKIP TESTS IS DISABLED. SKIP_TESTS OPTION IGNORED.  |
| system-tests  | chain-fee  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | chain-fee  |
| zwalletcli  | feat/chain-fee  |
| 0chain  | chain-fee  |
| blobber  | chain-fee  |
| authorizer  | chain-fee  |
| 0box  | chain-fee  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-03-15 15:56 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | ABILITY TO SKIP TESTS IS DISABLED. SKIP_TESTS OPTION IGNORED.  |
| system-tests  | chain-fee-remove-excess-faucet  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | chain-fee  |
| zwalletcli  | feat/chain-fee  |
| 0chain  | chain-fee  |
| blobber  | chain-fee  |
| authorizer  | chain-fee  |
| 0box  | chain-fee  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-03-15 19:53 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | ABILITY TO SKIP TESTS IS DISABLED. SKIP_TESTS OPTION IGNORED.  |
| system-tests  | chain-fee  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | chain-fee  |
| zwalletcli  | feat/chain-fee  |
| 0chain  | chain-fee  |
| blobber  | chain-fee  |
| authorizer  | chain-fee  |
| 0box  | chain-fee  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-03-18 03:22 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | chain-fee  |
| gosdk  | chain-fee  |
| zboxcli  | chain-fee  |
| zwalletcli  | feat/chain-fee  |
| 0chain  | chain-fee  |
| blobber  | chain-fee  |
| authorizer  | chain-fee  |
| 0box  | chain-fee  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-03-18 04:38 UTC, service-0chain commented
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | chain-fee  |
| gosdk  | chain-fee  |
| zboxcli  | chain-fee  |
| zwalletcli  | feat/chain-fee  |
| 0chain  | chain-fee  |
| blobber  | chain-fee  |
| authorizer  | chain-fee  |
| 0box  | chain-fee  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-03-31 06:25 UTC, service-0chain commented
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | chain-fee  |
| gosdk  | chain-fee  |
| zboxcli  | chain-fee  |
| zwalletcli  | feat/chain-fee  |
| 0chain  | chain-fee  |
| blobber  | chain-fee  |
| authorizer  | chain-fee  |
| 0box  | chain-fee  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-03-31 12:08 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | chain-fee  |
| gosdk  | chain-fee  |
| zboxcli  | chain-fee  |
| zwalletcli  | feat/chain-fee  |
| 0chain  | chain-fee  |
| blobber  | chain-fee  |
| authorizer  | chain-fee  |
| 0box  | chain-fee  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-04-01 01:03 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | chain-fee  |
| gosdk  | chain-fee  |
| zboxcli  | chain-fee  |
| zwalletcli  | feat/chain-fee  |
| 0chain  | chain-fee  |
| blobber  | chain-fee  |
| authorizer  | chain-fee  |
| 0box  | chain-fee  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-04-12 23:39 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | chain-fee  |
| gosdk  | chain-fee  |
| zboxcli  | chain-fee  |
| zwalletcli  | feat/chain-fee  |
| 0chain  | chain-fee  |
| blobber  | chain-fee  |
| authorizer  | chain-fee  |
| 0box  | chain-fee  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-04-13 14:27 UTC, service-0chain commented
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | chain-fee  |
| gosdk  | chain-fee  |
| zboxcli  | chain-fee  |
| zwalletcli  | feat/chain-fee  |
| 0chain  | chain-fee  |
| blobber  | chain-fee  |
| authorizer  | chain-fee  |
| 0box  | chain-fee  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-04-17 00:48 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | chain-fee  |
| gosdk  | chain-fee  |
| zboxcli  | chain-fee  |
| zwalletcli  | feat/chain-fee  |
| 0chain  | chain-fee  |
| blobber  | chain-fee  |
| authorizer  | chain-fee  |
| 0box  | chain-fee  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-04-17 04:57 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | chain-fee  |
| gosdk  | chain-fee  |
| zboxcli  | chain-fee  |
| zwalletcli  | feat/chain-fee  |
| 0chain  | chain-fee-v2  |
| blobber  | chain-fee  |
| authorizer  | chain-fee  |
| 0box  | chain-fee  |
| 0dns  | staging  |

2023-04-17 05:32 UTC, service-0chain commented
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | chain-fee  |
| gosdk  | chain-fee  |
| zboxcli  | chain-fee  |
| zwalletcli  | feat/chain-fee  |
| 0chain  | chain-fee-v2  |
| blobber  | chain-fee  |
| authorizer  | chain-fee  |
| 0box  | chain-fee  |
| 0dns  | staging  |

2023-04-17 12:41 UTC, merged