Set active default to true ls-miners
0chain/zwalletcli pull request #234
Opened 2023-04-11 13:42 UTC by Sriep

A brief description of the changes in this PR:

Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/zwalletcli/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- 0chain:
- Other: ...

2023-04-11 13:54 UTC, Kishan-Dhakan reviewed
Whether the user uses `--active` or not, they will always get active miners. I suggest to change the flag usage corresponding to the default value change, make it something like `--all` that returns both active and inactive providers if passed.

2023-04-11 13:57 UTC, Sriep commented
`ls-miners` or `ls-miners --active=ture` now returns active miners, and `ls-mienrs --active=false` returns inactive miners.

This is a change from the current situation where `ls-mines` returns inactive miners.

2023-04-11 14:04 UTC, Kishan-Dhakan commented
That makes sense but boolean flags are generally used such that if they're used they're true and if not used, false. Anyway it's subjective so I'll leave it with you

2023-05-21 00:36 UTC, peterlimg requested changes

2023-05-21 00:36 UTC, peterlimg commented on cmd/minersc.go
> +		active := true
Please update default flag value in line 627 and 633 as well, otherwise users could get confused.

2023-06-02 06:13 UTC, peterlimg approved these changes
LGTM

2023-06-02 06:13 UTC, merged