Feature/update 74
0chain/zwalletcli pull request #75
Opened 2021-12-20 00:30 UTC by Dmdv

Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/zwalletcli/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a branch at [0chain/system_test](https://github.com/0chain/system_test)

2021-12-28 23:59 UTC, cnlangzi commented
gosdk 1.4.0 is upgraded on https://github.com/0chain/zwalletcli/pull/78. so close this PR

2021-12-29 15:32 UTC, Dmdv commented
@cnlangzi This should be merged because those are my updates from zcnsc, nothing to do with other changes

2021-12-30 20:27 UTC, Dmdv commented
To complete review I need to update documentation

2021-12-31 03:31 UTC, cnlangzi requested changes, later dismissed

2021-12-31 03:31 UTC, cnlangzi commented on cmd/bridge-client-init.go
> +	_ = bridgeClientInit.MarkFlagRequired("password")
```suggestion
        bridgeClientInit.MarkFlagRequired("password") //nolint:errcheck
        bridgeClientInit.MarkFlagRequired("ethereumaddress") //nolint:errcheck
        bridgeClientInit.MarkFlagRequired("bridgeaddress") //nolint:errcheck
	bridgeClientInit.MarkFlagRequired("wzcnaddress") //nolint:errcheck
	bridgeClientInit.MarkFlagRequired("ethereumnodeurl") //nolint:errcheck
	bridgeClientInit.MarkFlagRequired("gaslimit") //nolint:errcheck
	bridgeClientInit.MarkFlagRequired("consensusthreshold") //nolint:errcheck
```

2021-12-31 03:31 UTC, cnlangzi commented on cmd/bridge-list-authorizers.go
> +	Run: func(_ *cobra.Command, _ []string) {
```suggestion
Run: func(*cobra.Command, []string) {
```

2021-12-31 03:31 UTC, cnlangzi commented on cmd/bridge-owner-init.go
> +	_ = bridgeOwnerInit.MarkFlagRequired("password")
```suggesion
        bridgeOwnerInit.MarkFlagRequired("password") //nolint:errcheck
	bridgeOwnerInit.MarkFlagRequired("ethereumaddress") //nolint:errcheck
	bridgeOwnerInit.MarkFlagRequired("bridgeaddress") //nolint:errcheck
	bridgeOwnerInit.MarkFlagRequired("wzcnaddress") //nolint:errcheck
	bridgeOwnerInit.MarkFlagRequired("ethereumnodeurl") //nolint:errcheck
	bridgeOwnerInit.MarkFlagRequired("gaslimit") //nolint:errcheck
```

2021-12-31 03:31 UTC, cnlangzi commented on cmd/ethereum-account-register.go
> +	_ = registerAccount.MarkFlagRequired("mnemonic")
```suggestion
	registerAccount.MarkFlagRequired("mnemonic") //nolint:errcheck
	registerAccount.MarkFlagRequired("password") //nolint:errcheck
```

2021-12-31 03:31 UTC, cnlangzi commented on cmd/ethereum-accounts-list.go
> +	Run: func(_ *cobra.Command, _ []string) {
```suggestion
Run: func(*cobra.Command, []string) {
```

2022-01-08 22:56 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/default_client_config  |
| gosdk  | feature/default_client_config  |
| zboxcli  | staging  |
| zwalletcli  | feature/update_74  |
| 0chain  | feature/zcnsc_eventsdb_storage  |
| blobber  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-01-16 21:08 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/zcnsc_zwallet_update_74  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | feature/update_74  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-01-28 00:17 UTC, Dmdv commented on cmd/bridge-client-init.go
> +	_ = bridgeClientInit.MarkFlagRequired("password")
Fixed

2022-01-28 00:18 UTC, Dmdv commented on cmd/bridge-list-authorizers.go
> +	Run: func(_ *cobra.Command, _ []string) {
Fixed

2022-02-04 04:34 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/zcnsc_zwallet_update_74  |
| gosdk  | staging  |
| zboxcli  | staging  |
| zwalletcli  | feature/update_74  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-02-04 13:15 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/zcnsc_zwallet_update_74  |
| gosdk  | feature/default_client_config  |
| zboxcli  | staging  |
| zwalletcli  | feature/update_74  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-02-05 08:08 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/zcnsc_zwallet_update_74  |
| gosdk  | feature/default_client_config  |
| zboxcli  | staging  |
| zwalletcli  | feature/update_74  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-02-06 00:04 UTC, stewartie4 commented
approving on behalf of @cnlangzi / @Sriep as per https://0chain.slack.com/archives/C02AV6MKT36/p1644104715711039?thread_ts=1644101141.278579&cid=C02AV6MKT36

2022-02-06 00:04 UTC, stewartie4 approved these changes

2022-02-06 00:14 UTC, merged